# Use an official PHP image as the base image
FROM php:8.2-apache

#
RUN docker-php-ext-install mysqli 

# Copy the application code
WORKDIR /var/www/html
COPY ./public/web-php/ .

# Change the owner of the application code
RUN chown -R www-data:www-data /var/www/html

# Enable the Apache rewrite module
RUN a2enmod rewrite

# Expose port 80
EXPOSE 80

# Start the Apache server
CMD ["apache2-foreground"]