apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-db-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  hostPath:
    path: ..\Docker\public\database\data
  accessModes:
    - ReadWriteOnce