apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-php-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  hostPath:
    path: ..\Docker\publlic\web-php
  accessModes:
    - ReadWriteOnce